# Generated by Django 3.2.18 on 2023-04-18 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_dui', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_datebirth', models.DateField()),
            ],
            options={
                'ordering': ['client_dui'],
            },
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('vault_id', models.AutoField(primary_key=True, serialize=False)),
                ('vault_serial_number', models.CharField(max_length=10)),
                ('vault_number_of_boxes', models.IntegerField()),
            ],
            options={
                'ordering': ['vault_serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('box_serial_number', models.CharField(max_length=10)),
                ('box_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoApp.client')),
                ('box_vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoApp.vault')),
            ],
            options={
                'ordering': ['box_serial_number'],
            },
        ),
    ]
